### ISSUE TITLE
[Bug]: url length limit

### ISSUE THREAD

**Issue by AAABBBCCCAAAA** [cnumr/ecoindex_api#130]
### What happened?

Hello sir I contact you to report bug in your api official url length max is 2083 chars and your api do not accept this size (below is url of size 379).

height	1960
url	"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAy5ctdzFrZe4Awsd1kw%3D%3D&hash=05B30BD9055986BD2EE8F5A199D973&cid=u.Olw7yzo_CdpULe.-yA3S28H_64TvF2acb1NxBopd-ZAqXMMRD1TeiM69GGPHAkklgHIdirA-qQIxvbJhrjeVy9IE1rOwH9imodn~PBuwB1FZdOWpp3xL_ocqweuG_&t=fe&referer=https%3A%2F%2Fwww.leboncoin.fr%2F&s=2089&e=8302bf5d5a4c3eef1bc6f25ed604931c7605f831275f3bcaa1d07e423e14d75a"
width	1080

detail	Object { exception: "DataError", args: […], message: null }
args	[ "(pymysql.err.DataError) (1406, \"Data too long for column 'url' at row 1\")" ]
exception	"DataError"
message	null
You - 2022-05-23, 19:29:11

### Version

^3.6

### What OS do you use?

Windows

### urls

https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAy5ctdzFrZe4Awsd1kw%3D%3D&hash=05B30BD9055986BD2EE8F5A199D973&cid=u.Olw7yzo_CdpULe.-yA3S28H_64TvF2acb1NxBopd-ZAqXMMRD1TeiM69GGPHAkklgHIdirA-qQIxvbJhrjeVy9IE1rOwH9imodn~PBuwB1FZdOWpp3xL_ocqweuG_&t=fe&referer=https%3A%2F%2Fwww.leboncoin.fr%2F&s=2089&e=8302bf5d5a4c3eef1bc6f25ed604931c7605f831275f3bcaa1d07e423e14d75a

### Relevant log output

```shell
detail	Object { exception: "DataError", args: […], message: null }
args	[ "(pymysql.err.DataError) (1406, \"Data too long for column 'url' at row 1\")" ]
exception	"DataError"
message	null
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
While url field is well configured, it seems that SQLModel (or SQLAlchemy) does not take into account the max length property (set to 2083) of the field and create a field of type `varchar(255)` instead of `text`

For now, I updated the production database and set the url field type to `text`.

**Comment by vvatelot** [comment]
I reopen this issue to keep a trace, ans investigate further
