### ISSUE TITLE
[Enhancement]: Améliorer les retours de l'API

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_api#309]
# Aucune mesure disponible pour https://www.yourdomain.tld
> https://bff.ecoindex.fr/api/results/?url=https://novagaiaa.fr/test
L'API retourne une erreur 404, mais retourne un arbre de données vide.
```json
{
  "count": 0,
  "latest-result": {
    "id": "",
    "grade": "",
    "score": 0,
    "date": "",
    "requests": 0,
    "size": 0,
    "nodes": 0,
    "url": "",
    "color": ""
  },
  "older-results": null,
  "host-results": null
}
```
## Proposition
- Utiliser le code [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)
- Ne pas retourner d'arbre vide, mais un message.
```json
{
  "code": 204,
  "message": "Aucune mesure disponible pour https://www.yourdomain.tld"
}
```
# Aucune mesure disponible pour la page https://www.yourdomain.tld/test
> https://bff.ecoindex.fr/api/results/?url=https://novagaia.fr/test
L'API retourne une erreur 200, mais retourne un `latest-result` vide.
```json
{
  "count": 17,
  "latest-result": {
    "id": "",
    "grade": "",
    "score": 0,
    "date": "",
    "requests": 0,
    "size": 0,
    "nodes": 0,
    "url": "",
    "color": ""
  },
  "older-results": null,
  "host-results": [
    {
      "id": "46df881f-0cc3-4153-9fa9-871f65b22362",
      "grade": "B",
      "score": 74,
      "date": "2023-03-21T22:30:57",
      "requests": 39,
      "size": 1210.65,
      "nodes": 264,
      "url": "https://novagaia.fr/offres/creez-un-site-web-performant-et-moins-polluant/",
      "color": "#51B84B"
    },
    {
      "id": "430b0d3c-0bd2-4b75-bdea-8d410f2615d3",
      "grade": "B",
      "score": 72,
      "date": "2023-03-21T22:29:10",
      "requests": 55,
      "size": 779.939,
      "nodes": 273,
      "url": "https://novagaia.fr/",
      "color": "#51B84B"
    },
    // ...
  ]
}
```
## Proposition
- Retourner un code 204 ;
- Un message ;
- Ne pas retourner `latest-result`.
> Je ne sais pas comment gérer, à par tester que l'`id` est vide...
```json
{
  "code": 204,
  "message": "Aucune mesure disponible pour la page https://www.yourdomain.tld/test",
  "count": 17,
  "latest-result": {
    "id": "",
    "grade": "",
    "score": 0,
    "date": "",
    "requests": 0,
    "size": 0,
    "nodes": 0,
    "url": "",
    "color": ""
  },
  "older-results": null,
  "host-results": [
    {
      "id": "46df881f-0cc3-4153-9fa9-871f65b22362",
      "grade": "B",
      "score": 74,
      "date": "2023-03-21T22:30:57",
      "requests": 39,
      "size": 1210.65,
      "nodes": 264,
      "url": "https://novagaia.fr/offres/creez-un-site-web-performant-et-moins-polluant/",
      "color": "#51B84B"
    },
    {
      "id": "430b0d3c-0bd2-4b75-bdea-8d410f2615d3",
      "grade": "B",
      "score": 72,
      "date": "2023-03-21T22:29:10",
      "requests": 55,
      "size": 779.939,
      "nodes": 273,
      "url": "https://novagaia.fr/",
      "color": "#51B84B"
    },
    // ...
  ]
}
```
# Atteinte de limit de 10 test/j/domain
J'ai une erreur 500, pas d'infos et l'extension chrome ne sait pas gérer, car elle mouline dans vide...
## Proposition
- code erreur:  [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)
- message: Le domain https://www.yourdomain.tld/test a atteint le nombre des `n` mesures proposées par Ecoindex pour la journée du DD/MM/YY
- nombre de tests restants sur ce domain pour cette journée.
```json
{
  "code": 429,
  "message": "Le domain https://www.yourdomain.tld/test a atteint le nombre des `n` mesures proposées par Ecoindex pour la journée du DD/MM/YY",
  "count": 17,
  "latest-result": {
    "id": "",
    "grade": "",
    "score": 0,
    "date": "",
    "requests": 0,
    "size": 0,
    "nodes": 0,
    "url": "",
    "color": ""
  },
  "older-results": null,
  "host-results": [
    {
      "id": "46df881f-0cc3-4153-9fa9-871f65b22362",
      "grade": "B",
      "score": 74,
      "date": "2023-03-21T22:30:57",
      "requests": 39,
      "size": 1210.65,
      "nodes": 264,
      "url": "https://novagaia.fr/offres/creez-un-site-web-performant-et-moins-polluant/",
      "color": "#51B84B"
    },
    {
      "id": "430b0d3c-0bd2-4b75-bdea-8d410f2615d3",
      "grade": "B",
      "score": 72,
      "date": "2023-03-21T22:29:10",
      "requests": 55,
      "size": 779.939,
      "nodes": 273,
      "url": "https://novagaia.fr/",
      "color": "#51B84B"
    },
    // ...
  ]
}
```
# Demande de mesure d'une URL
Pourquoi recevoir un numéro de task (ce devrait être du json), plutôt qu'attendre et retourner l'arbre ?
```json
"35c64f8e-9bca-4c0d-b5db-9dda4d1c6fe5"
```
## Proposition
- renvoyer le code [201](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201)
- renvoyer l'arbre rempli par le test courant dans `result` ;
- indiquer le nombre de test restant dans `testLeftToday`.
```json
{
  "code": 201,
  "testLeftToday": 4,
  "count": 17,
  "result": {
      "id": "46df881f-0cc3-4153-9fa9-871f65b22362",
      "grade": "B",
      "score": 74,
      "date": "2023-03-21T22:30:57",
      "requests": 39,
      "size": 1210.65,
      "nodes": 264,
      "url": "https://novagaia.fr/offres/creez-un-site-web-performant-et-moins-polluant/",
      "color": "#51B84B"
    },
}
```

**Comment by vvatelot** [comment]
Hello @hrenaud, merci beaucoup pour tes retours...

Alors, pour reprendre point par point :slightly_smiling_face: 

## Aucune mesure disponible pour une url

Pourquoi pas modifier le message en réponse. Mais il faut faire l'issue sur le projet [BFF](https://github.com/cnumr/ecoindex_bff) :wink: 

## Pas de `latest-result`

Je pense que le code réponse 200 est correct (en tout cas, je n'en trouve pas de meilleur...)
On peut voir pour modifier la réponse et supprimer le `latest-result` vide. Encore une fois, Issue à créer sur le repo BFF :smile: 

## Limitation à 10 analyses / jour / domaine

C'est une régression... Normalement on est censé renvoyer une 429 : https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/cnumr/ecoindex_api/main/docs/openapi.json#tag/Tasks/operation/Add_new_ecoindex_analysis_task_to_the_waiting_queue_v1_tasks_ecoindexes_post

On retrouve les infos de la dernière analyse.

Lorsque l'on poste une nouvelle analyse, on renvoie en header le nombre d'analyses restantes ` x-remaining-daily-requests: 0 `

## Test d'une url

Non, c'est justement fait exprès: Renvoyer le plus rapidement possible l'ID de la tâche qui a été créée. Charge au client de venir interroger le serveur pour voir si la tâche a été traitée. J'ai volontairement mis en plein un fonctionnement asynchrone pour des raisons de performances et de praticité.

Par contre, peut être que ce n'est pas assez bien documenté et qu'il faudrait donner un exemple d'utilisation complet ?



> NB: Au risque d'être désobligeant, si tu peux créer une issue par sujet ? :wink: Ce qui permet de traiter les sujets unitairement et d'améliorer la lisibiltié

**Comment by vvatelot** [comment]
Je me permet de créer une issue à part pour l'erreur 500 sur les limites par jours parce qu'il s'agit d'un hotfix que je dois faire en urgence... :rotating_light:
