### ISSUE TITLE
[Bug]: Trop d'URLs tue l'analyse

### ISSUE THREAD

**Issue by pirmax** [cnumr/ecoindex_api#317]
### What happened?

J'ai l'impression que les fenêtres de Chrome ne se ferment pas pendant le scrapping quand il y a des erreurs du côté de l'API ou du scrap, j'ai remonté une erreur déjà sur l'issue #316 mais là ça devient problématique pour l'analyse de plusieurs URLs (environ 5000).

Mon _docker-compose.override.yml_ :

```
x-logging: &default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file
services:
  worker:
    entrypoint: |
      bash -c  "celery -A worker.tasks worker -P threads --concurrency=1"
    deploy:
      replicas: 3
  api:
    logging: *default-logging
  flower:
    logging: *default-logging
```

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pirmax** [comment]
![Capture d’écran 2023-03-27 à 17 55 51](https://user-images.githubusercontent.com/1739235/227996499-378e91b1-5ca1-4099-b6ab-31de2ef5015b.png)

J'ajoute ça aussi, visiblement, même après reboot du VPS, on a encore des "Chrome en défaut".

**Comment by vvatelot** [comment]
Bonjour @pirmax merci pour les infos, je vais essayer de regarder ça.
En complément, sur quelle version de l'API es tu ? Quelles sont les caractéristiques de ton serveur ?

**Comment by pirmax** [comment]
On bosse sur la dernière version (v2.4.0). Et nous sommes sur une Debian 9.

**Comment by vvatelot** [comment]
J'ai peut être une idée:
La tâche d'analyse a un retry à 5... Et peu importe l'erreur rencontrée (ici, erreur d'enregistrement mysql), toute la tâche est relancée :disappointed: 
Si tu essayes de supprimer les lignes 42-42 de `worker/tasks.py` on va éviter le retry et tout de suite tomber en erreur et là ça devrait aller mieux (sous réserve que je règle l'autre bug...)

**Comment by vvatelot** [comment]
OK, top déjà une bonne nouvelle. Quand tu dis "présente dans flower", dans quel statut ? Si jamais tu as un screenshot ?

**Comment by pirmax** [comment]
![image](https://user-images.githubusercontent.com/1739235/228279914-451aa2b3-1909-45a1-9d74-fe098e13bb95.png)

Elles sont en "success" dans Flower.

Mais j'ai l'impression que toutes les URLs envoyées (9576 URLs) ne sont pas présentes dans la totalité sur Flower. Je vais regarder en base de données.

**Comment by pirmax** [comment]
En faite, elles ne se sont pas toutes envoyées suite à une [422 Unprocessable Entity](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/422).

J'ai donc que 256 résultats dans la table "apiecoindex". 9576 URLs envoyées (qui ne sont envoyées partiellement donc).
Et j'ai calculé 10 items affichés pour 34 pages (+1 page avec un seul item) = 341 lignes dans le tableau...

**Comment by vvatelot** [comment]
OK, si tu arrives à en savoir plus sur la 422 ?

**Comment by pirmax** [comment]
> OK, si tu arrives à en savoir plus sur la 422 ?

Je suis en train de regarder en ce moment même. Je te tiens au courant.

**Comment by pirmax** [comment]
Bon, c'est peut-être normal mais dès que j'envoie des URLs via l'API, elles ne sont pas tout de suite disponible dans Flower. Je viens d'envoyer 10K URLs, pas de problème à l'heure actuelle.

**Comment by vvatelot** [comment]
Je t'avoue que je n'ai pas effectué de stress test de cette envergure ! :thinking: 
J'imagine que si le serveur est fortement chargé, il y a peut être un petit délai d'affichage dans flower. 

Dans tous les cas je suis curieux de savoir comment ça se passe. Tu me feras un retour ?

Au fait, normalement j'ai corrigé le problème du multithread dans l'API, donc tu dois pouvoir tester avec `--concurrency=2` par exemple...

**Comment by pirmax** [comment]
Si ça peut aider...

J'ai trouvé ça en tapant cette commande dans le container d'un des 3 workers : `celery -A worker.tasks worker` ou `celery -A worker.tasks status`

![image](https://user-images.githubusercontent.com/1739235/228460939-da75b6ec-a9da-48c6-b10f-54709365a0c8.png)

**Comment by vvatelot** [comment]
Les urls apparaissent elles dans flower ? (Celles qui n'ont pas été traitées)... Pour savoir si le problème se pose au moment de l'ajout d'une analyse ou au moment du traitement...

**Comment by pirmax** [comment]
En fait, elles n'apparaissent pas toutes dans Flower, j'obtiens bien un UUID via le POST à l'API quand j'envoie une ou plusieurs URLs mais quand j'envoie beaucoup d'URLs, les informations sont perdues, elles ne sont même pas dans la table "apiecoindex" dans MySQL.

**Comment by vvatelot** [comment]
Ça me paraît être une vieille issue quand même... :thinking: 
Peut être en essayant de debug. Là je suis en train de tester sur 1000 urls sur mon PC... Ça dépile, j'en suis à 350 urls traitées. J'utilise le `docker-composer.override.yaml` suivant pour debuguer:

```
services:
  worker:
    entrypoint: |
      bash -c  "celery -A worker.tasks worker -P threads --concurrency=1"
```

Pour info, le bug du multithread étant résolu, plus besoin d'utiliser l'option `--max-concurrency`
