### ISSUE TITLE
[Bug]: Erreur lors du déploiement - ERROR [worker requirements-stage 6/9] 

### ISSUE THREAD

**Issue by hviricel** [cnumr/ecoindex_api#357]
Bonjour !

### What happened?

Depuis la branche Main

Lors du build : docker compose up -d --build

Cette erreur apparait et bloc le déploiement :

=> ERROR [worker requirements-stage 6/9] RUN poetry export --with=worker --output=requirements.txt --without-hashes

------
 > [worker requirements-stage 6/9] RUN poetry export --with=worker --output=requirements.txt --without-hashes:
#0 0.890 
#0 0.891 Group(s) not found: worker (via --with)
------
failed to solve: process "/bin/sh -c poetry export --with=worker --output=requirements.txt --without-hashes" did not complete successfully: exit code: 1

Je n'avais pas cette erreur lors de précédent déploiement. 

### Version

^3.6

### What OS do you use?

Linux

### Relevant log output

```shell
=> ERROR [worker requirements-stage 6/9] RUN poetry export --with=worker --output=requirements.txt --without-hashes

------
 > [worker requirements-stage 6/9] RUN poetry export --with=worker --output=requirements.txt --without-hashes:
#0 0.890 
#0 0.891 Group(s) not found: worker (via --with)
------
failed to solve: process "/bin/sh -c poetry export --with=worker --output=requirements.txt --without-hashes" did not complete successfully: exit code: 1
```

Merci beaucoup pour votre code et pour votre aide

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Bonsoir @hviricel peux tu essayer avec la branche fix/docker-poetry-export-group ?
J'ai l'impression que poetry a été mis à et est moins tolérant sur une erreur que je trainais depuis quelques temps...

**Comment by vvatelot** [comment]
OK, je merge et met à jour le projet ! Merci pour ta contribution !
