### ISSUE TITLE
[Bug]: L'API retourne l'erreur "You can't write against a read only replica"

### ISSUE THREAD

**Issue by hviricel** [cnumr/ecoindex_api#365]
### What happened?

Suite à l'installation du service sur Scaleway (le soucis était le même chez Digital Ocean)

Après quelques jours d'utilisation
Lors d'un appel à l'API, le message suivant est retourné : 
"You can't write against a read only replica"

(retour complet :  { ["detail"]=> object(stdClass)#15113 (3) { ["args"]=> array(1) { [0]=> string(44) "You can't write against a read only replica." } ["exception"]=> string(16) "OperationalError" ["message"]=> NULL } }  )

 
Apparemment le soucis est lié à Redis et à l'accessibilité public du port 6379

Une solution identifiée serait :

Remediation of this issue will take just a few minutes and is relatively straightforward. You will need to open /etc/redis/redis.conf and uncomment (remove the “#”) or modify the line beginning with:
 
#bind 127.0.0.1 ::1
 
Afterwards, restart redis with:
 
sudo systemctl restart redis

Merci pour ton aide

A dispo

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hviricel** [comment]
@vvatelot C'est une instance ubuntu 20.04 prépackagé avec Docker version 24.0.2.
Cœurs : 3
RAM : 4 Go
DD : 50Go

J'ai trouvé cette page : https://www.scaleway.com/en/docs/compute/gpu/reference-content/docker-images/

**Comment by vvatelot** [comment]
OK, ma question était plus orientée: Comment as tu déployé le service ? Full Docker ? Redis à part ?... :slightly_smiling_face:

**Comment by hviricel** [comment]
@vvatelot ah ^^
Full docker, j'ai déployé l'image du repo tout simplement :)

**Comment by vvatelot** [comment]
Etrange... Première fois que j'ai ce souci

**Comment by vvatelot** [comment]
Je vais retester un installation fraîche demain

**Comment by hviricel** [comment]
@vvatelot effectivement, en relançant le serveur ça fonctionne ! Merci
Par contre, je suis étonné du faible nombre d'analyse qu'il a fallut pour le déclencher

**Comment by vvatelot** [comment]
Effectivement, 3 analyses c'est vraiment très peu... :thinking: 
De mon côté j'avais observé des problèmes à partir de plus de 10000 analyses...

**Comment by hviricel** [comment]
@vvatelot 
Bonjour, 
J'ai toujours le problème mentionné, sauf que depuis la dernière fois il n'y a eu aucun appel à l'API
A dispo pour creuser le problème

**Comment by vvatelot** [comment]
OK, est ce qu'il y a un autre service qui pourrait bloquer le serveur ? :thinking: 
Sinon, il faudrait qu'on puisse regarder ça ensemble, parce que là je n'ai pas de solution

**Comment by hviricel** [comment]
@vvatelot il n'y a que cette image sur le serveur.
Je suis dispo pour que l'on regarde ensemble, quelles sont tes disponibilités ?
