### ISSUE TITLE
[Bug]: Out of memory: killed process xxxxx (chrome)

### ISSUE THREAD

**Issue by trineon89** [cnumr/ecoindex_api#406]
### What happened?

After some scans (15-20 about) the server overloads.
The API runs on an ESX-Server with 4 GB of RAM and 4 vCPUs. I incremented it to 12 GB RAM and 8 vCPUs, but the problem occurs after some scans again. If I connect to the flower interface (localip:5555) I see the tasks running well and completing in 5-10 seconds, then the last one takes 400+ seconds and results in a failure and the interface gets inaccessible.
Only way to fix is to restart the virtualized machine.

I also did a fresh install, clean Debian only with the needed dependencies, but the same behavior.

The tasks/scans are filled one-by-one, after the last one finishes and gets a result, a new one gets filled. This error first appeared 2 months ago and is still present until today.

Attached is the output from: ps -aux

What output should/can I attach to give you more feedback?

Thanks in advance
[ps -aux.txt](https://github.com/cnumr/ecoindex_api/files/12476349/ps.-aux.txt)

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Hello @trineon89 , thanks for your issue.
What version of the API are you trying to deploy ?

I observed that the latest version has the issue you mentioned. In production I rolled back to the [v3.0.0](https://github.com/cnumr/ecoindex_api/releases/tag/v3.0.0). Can you try with this version ?

**Comment by vvatelot** [comment]
BTW, I saw your project https://github.com/trineon89/AutismePlangDisplayApp. What is it about ? Is it still alive ?

**Comment by trineon89** [comment]
> BTW, I saw your project https://github.com/trineon89/AutismePlangDisplayApp. What is it about ? Is it still alive ?

It's a graphical interface we use internally for displaying who is working where and when. There's also a server code who manages the displays (Sony Bravia Pro's) to turn them on or shut them down. (This is a different repo).
Yes, we are using it still and it is live

**Comment by trineon89** [comment]
> Hello @trineon89 , thanks for your issue. What version of the API are you trying to deploy ?
> 
> I observed that the latest version has the issue you mentioned. In production I rolled back to the [v3.0.0](https://github.com/cnumr/ecoindex_api/releases/tag/v3.0.0). Can you try with this version ?

I rolled back to the mentioned tag and it works now as intended.
Thanks
