### ISSUE TITLE
Ranking de la page

### ISSUE THREAD

**Issue by vvatelot** [cnumr/ecoindex_api#71]
# Afin de
Pouvoir situer notre analyse de page sur un panel d'analyse

# Je veux
Indiquer le "ranking" de cette analyse sur l'échantillon total

# Infos
- Je veux modifier le modèle de données du résultats d'une analyse pour la requête GET /ecoindexes/{id} pour ajouter un champs `initial_ranking` 
- Enregistrer en base cette donnée `initial_ranking` au format JSON du type 
```json
{
  "rank": 1234,
  "total": 987654
}
```
- Faut il rajouter un champs ranking pour renvoyer le classement de cette analyse à un instant T...?
- Il faut également créer une commande d'initialisation pour gérer toutes les analyses déjà enregistrées en base

**Comment by vvatelot** [comment]
@aureliebaton et @Bastou je propose dans un premier temps d'enregistrer le ranking initial lors de l'analyse en BDD...
Je propose de faire une autre fonctionnalité par la suite pour "rafraichir" ce rankning et récupérer le classement à un instant T... Qu'en pensez vous ?

**Comment by aureliebaton** [comment]
Ca me semble être une bonne idée en effet !
